# A Simple Docker compose stack for running both front end and back end containers
version: '3'
x-project_name: "fan-controller-web-stack"
services:
  
  back-end:
    build: ./BackEnd
    container_name: back-end
    ports:
      - "5000:5000"
    environment:
      - MOCK=""
   
  front-end:
    build: ./FrontEnd
    container_name: front-end
    ports:
      - "8000:80"
    depends_on:
      - back-end
