# A Simple Docker compose stack for running both front end and back end containers
version: '3'
x-project_name: "fan-controller-web-stack"
services:
  
  back-end:
    build: ./BackEnd
    container_name: back-end
    ports:
      - "5000:5000"
    environment:
      - MOCK=${MOCK}
    privileged: true # Required for GPIO access

  front-end:
    build: ./FrontEnd
    container_name: front-end
    ports:
      - "5001:80"
    depends_on:
      - back-end
