name: Build

on: [push]

jobs:
  docker-build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Packages
        run: |
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint .

      - name: Check Dockerfiles
        run: |
          hadolint --failure-threshold error --verbose ./BackEnd/Dockerfile 
          hadolint --failure-threshold error --verbose ./FrontEnd/Dockerfile

      - name: Build BackEnd Dockerfile
        run: docker build ./BackEnd -t pythonwebapp_backend --build-arg MOCK="mock"

      - name: Build FrontEnd Dockerfile
        run: docker build ./FrontEnd -t pythonwebapp_frontend

      - name: Run FrontEnd Dockerfile
        run: |
          docker run -d -p 8000:80 --name frontend pythonwebapp_frontend:latest
          sleep 2
          docker stop frontend

      - name: Run BackEnd Dockerfile
        run: |
          docker run -d -p 5000:80 --name backend pythonwebapp_backend:latest
          sleep 2
          docker stop backend

  docker-compose-build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check valid Docker Compose file
        run: |
          docker-compose config --quiet || { echo "Invalid Docker Compose file"; exit 1; }

      - name: Run Docker Compose
        run: |
          touch .env
          echo "MOCK=mock" >> .env
          docker-compose up -d
          sleep 2
          docker-compose down

  scripts:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Packages
        run: |
          sudo apt-get install shellcheck

      - name: Check Shell Scripts
        run: |
          shellcheck BackEnd/run.sh
          shellcheck FrontEnd/run.sh

      - name: Run BackEnd Script
        run: |
          chmod +x ./BackEnd/run.sh
          cd BackEnd
          ./run.sh mock
          cd ..

      - name: Run FrontEnd Script
        run: |
          chmod +x ./FrontEnd/run.sh
          cd FrontEnd
          ./run.sh
          cd ..
