name: Build Dockerfiles

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test BackEnd Dockerfile
        run: docker build ./BackEnd

      - name: Test FrontEnd Dockerfile
        run: docker build ./FrontEnd
