name: Static Analysis

on: [push]

jobs:
  frontend:
    name: Frontend Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Packages
        run: |
          sudo apt-get install npm -y
          sudo npm install -g htmllint-cli
          sudo npm install -g csslint
          sudo npm install -g eslint
          npm init -y
          npm init @eslint/config
      - name: Static Analysis
        run: |
          cd FrontEnd
          htmllint src/*.html
          csslint src/*.css
          eslint src/*.js

  backend:
    name: Backend Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Packages
        run: |
          sudo apt-get install pip -y
          pip install pylint
          pip install -r BackEnd/requirements.txt

      - name: Static Analysis
        run: |
          pylint --fail-under=4 ./BackEnd/src/*.py  # Under 4 due to issues with the runner not being a raspberry pi
          
  Markdown_Lint_Check:
        name: Markdown Lint Check
        runs-on: ubuntu-latest
        steps:
            - name: Install markdownlint-cli
              run: npm install -g markdownlint-cli

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run markdownlint
              run: markdownlint '**/*.md'
              
              
  Shell-Lint_Check:
        name: Shell Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Download Packages
              run: |
                sudo apt-get install shellcheck 
            - name: Shell Check
              run: |
                shellcheck **/*.sh         

  YAML_Lint_Check:
    name: YAML Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Install yamllint
        run: sudo apt install yamllint
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run yamllint
        run: |
          echo "Checking YAML files"
          yamllint -c .yamllint.yml .github/**/**.yml
          yamllint -c .yamllint.yml **.yml