name: Test

on: [push]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Packages
        run: |
          pip install pylint
          pip install requirements.txt

      - name: Static Analysis
        run: |
          pylint ./BackEnd/src/*.py

      - name: Run Unit Tests
        run: |
          echo "To be implemented"
